services:
  backend:
    image: ${BACKEND_IMAGE} #
    container_name: manalgak-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env #
    networks:
      - manalgak-network

  frontend:
    image: ${FRONTEND_IMAGE} #
    container_name: manalgak-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env #
    depends_on:
      - backend
    networks:
      - manalgak-network

  nginx:
    image: nginx:latest
    container_name: manalgak-nginx
    ports:
      - "80:80" # 외부 80포트 개방
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #
    depends_on:
      - frontend
      - backend
    networks:
      - manalgak-network

networks:
  manalgak-network:
    driver: bridge