version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: manalgak-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - manalgak-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: manalgak-frontend
    restart: unless-stopped
    ports:
      - "3030:3000"
    depends_on:
      - backend
    networks:
      - manalgak-network
networks:
  manalgak-network:
    driver: bridge